ionic-team/starters

- package.json
> chore(package): bump deps

- ionic-angular/official/super/src/assets/i18n/de.json
"Nützen" is wrong, should be "Nutzen" and "vielzahl" should be "Vielzahl"
> Typos in de translation

- ionic-angular/official/super/src/app/app.component.ts
- ionic-angular/official/super/src/assets/i18n/zh-cmn-Hans.json
- ionic-angular/official/super/src/assets/i18n/zh-cmn-Hant.json
Add zh-cmn-Hans.json and zh-cmn-Hant.json.
Use the correct zh-* file via getBrowserCultureLang()
> i18n: add zh-cmn-Hans.json and zh-cmn-Hant.json for super

- CONTRIBUTING.md
- src/build.ts
- src/definitions.ts
- src/utils.ts
Tested successfully with [this `ionic.starter.json` file](https://github.com/morphatic/ionic-neat/blob/d853d8db41a6d1568c6549f00003f4cc5359697f/ionic.starter.json) from the [starter template I've been developing](https://github.com/morphatic/ionic-neat).
This is a proof-of-concept for the idea expressed in #29. I won't be upset or offended if this PR gets rejected.
> Merge other config files: tsconfig, gitignore (potential fix for #29)

- ionic-angular/official/aws/README.md
- ionic-angular/official/aws/ionic.starter.json
- ionic-angular/official/aws/src/app/app.module.ts
- ionic-angular/official/aws/src/pages/tasks/tasks.ts
- ionic-angular/official/aws/src/providers/aws.dynamodb.ts
Some small fixes :)
Thank you!
> README improvements and typescript @types/node dependency

- angular/official/blank/src/app/pages/home/home.page.html
> fix(blank): remove ion-page element

- angular/base/package.json
Angular 5.x supports TypeScript 2.6.x
> chore(angular): bump typescript

- angular/official/blank/src/app/pages/home/home.module.ts
> chore(blank): add form module in template blank

- angular/official/sidemenu/src/app/list/list.page.html
Matching page title with sidemenu label
> Updating Page Title

- angular/official/blank/src/app/home/home.page.html
- angular/official/sidemenu/src/app/home/home.page.html
- angular/official/tabs/src/app/home/home.page.html
- ionic1/official/tabs/www/templates/tab-dash.html
https://developers.google.com/web/tools/lighthouse/audits/noopener
> Missing noopener

- angular/base/angular.json
when run `ng g library my-lib` create folder library with name `undefined`
> newProjectRoot undefined

- angular/base/src/index.html
Ref https://github.com/ionic-team/ionic-cli/issues/3665
I wonder how this happened.....
> fix(): bad formatting in template

- react/official/tabs/src/App.tsx
related https://github.com/ionic-team/starters/issues/739
> fix(react): enable redirect

- angular/base/src/app/app.component.scss
Closes https://github.com/ionic-team/starters/issues/865
> chore(): update styles comment

- react/official/sidemenu/src/components/Menu.tsx
> fix(menu): unhide menu link in desktop view

- react/official/sidemenu/src/pages/Home.tsx
- react/official/tabs/src/pages/Tab1.tsx
> fix: apply classes correctly

- react/official/blank/src/pages/Home.tsx
- react/official/sidemenu/src/pages/Home.tsx
- react/official/sidemenu/src/pages/List.tsx
- react/official/tabs/src/pages/Details.tsx
- react/official/tabs/src/pages/Tab1.tsx
- react/official/tabs/src/pages/Tab2.tsx
- react/official/tabs/src/pages/Tab3.tsx
> fix(react): wrap pages in IonPage

- angular/base/.gitignore
- ionic-angular/base/.gitignore
- ionic1/base/.gitignore
Ignoring the resources directory break appflow builds
> fix(): remove resources for gitignore

- angular/base/package.json
update to @ionic/angular-toolkit to ^2.1.1
> update(package): @ionic/angular-toolkit for dynamic import

- ionic-angular/base/package.json
- Update `ionic-angular`
- Update `@ionic/app-scripts`
- Remove `@angular/http` (to encourage use of `@angular/common/http`)
- Remove tildes to solidify versions
> chore(deps): Updating ionic-angular base deps

- angular/base/src/index.html
- react/base/public/index.html
Causes system UI components such as scrollbar to render properly in dark mode
> chore(starters): add color-scheme meta tag

- angular/official/blank/src/app/app-routing.module.ts
- angular/official/blank/src/app/home/home-routing.module.ts
- angular/official/blank/src/app/home/home.module.ts
- angular/official/list/src/app/app-routing.module.ts
- angular/official/list/src/app/home/home-routing.module.ts
- angular/official/list/src/app/home/home.module.ts
- angular/official/tabs/src/app/tab1/tab1-routing.module.ts
- angular/official/tabs/src/app/tab1/tab1.module.ts
- angular/official/tabs/src/app/tab2/tab2-routing.module.ts
- angular/official/tabs/src/app/tab2/tab2.module.ts
- angular/official/tabs/src/app/tab3/tab3-routing.module.ts
- angular/official/tabs/src/app/tab3/tab3.module.ts
- angular/official/tabs/src/app/tabs/tabs-routing.module.ts
This PR is to change the blank and tabs starter so that they use page based routing modules instead of using the forChild method.
> Add routing modules.

- angular/base/tsconfig.app.json
- angular/base/tsconfig.json
- angular/base/tsconfig.spec.json
- angular/base/tslint.json
This will hopefully [solve issues that I experienced when upgrading](https://travis-ci.org/github/oktadeveloper/ionic-jhipster-starter/builds/687078157#L534) to the latest blank starter.
Solution found at https://github.com/angular/angular-cli/issues/17066.
> Update tsconfig files to match Angular CLI

- angular/base/tslint.json
Ionic CLI create Page Component Name "**Page".
> fix(angular): allow Component name "**Page"

- angular/base/src/theme/variables.scss
- react/base/src/theme/variables.css
blocked by https://github.com/ionic-team/ionic-framework/pull/21756
merge after framework 5.3 ships
> chore(): update card dark mode css variable

- react/base/package.json
to be able to install on npm 7
> fix: use latest react-scripts dependency

- ionic-angular/official/sidemenu/src/pages/home/home.html
closes https://github.com/ionic-team/starters/issues/1688
> chore(ionic-angular): use v3 link in sidemenu template, not v2

- angular/base/package.json
closes https://github.com/ionic-team/starters/issues/1695
> fix: remove duplicated @angular/compiler entry

- vue/official/blank/src/views/HomePage.vue
- vue/official/list/src/views/HomePage.vue
- vue/official/list/src/views/ViewMessagePage.vue
- vue/official/sidemenu/src/views/FolderPage.vue
- vue/official/tabs/src/components/ExploreContainer.vue
- vue/official/tabs/src/views/Tab1Page.vue
- vue/official/tabs/src/views/Tab2Page.vue
- vue/official/tabs/src/views/Tab3Page.vue
- vue/official/tabs/src/views/TabsPage.vue
Make the Vue starters consistent with one another.
Provide better TypeScript support.
Improve the debugging experience.
> fix(vue): add defineComponent calls and name parameter

- package.json
- src/commands/build.ts
- src/commands/deploy.ts
- src/commands/find-redundant.ts
- src/commands/generate-checksum.ts
- src/commands/test.ts
- src/definitions.ts
- src/index.ts
- src/lib/build.ts
- src/utils/index.ts
- tsconfig.json
- tslint.json
Updates the various build tools and dependencies to their latest version.
Need to validate that this does not include any breaking changes with how the starters are deployed.
> Dep updates

- angular/base/.browserslistrc
Updates the browserslist file in accordance with the Ionic v6 browser support: https://ionicframework.com/docs/reference/browser-support
See: https://forum.ionicframework.com/t/ionic-6-default-project-white-screen-on-android-30-or-below-when-using-prod/228087/10 for more information
> chore(angular): update browserslist

- README.md
- angular/base/package.json
- angular/base/src/test.ts
- angular/base/tsconfig.json
- angular/official/list/src/app/message/message.component.ts
- angular/official/list/src/app/view-message/view-message.page.ts
- angular/official/sidemenu/src/app/folder/folder.page.ts
- angular/official/tabs/src/app/explore-container/explore-container.component.ts
Updates the Angular starters to use Angular 15 by default.
> feat(angular): update starters to angular 15

- .github/workflows/main.yml
- react-vite/official/blank/ionic.starter.json
- react-vite/official/list/ionic.starter.json
- react-vite/official/sidemenu/ionic.starter.json
- react-vite/official/tabs/ionic.starter.json
- react/official/blank/ionic.starter.json
- react/official/list/ionic.starter.json
- react/official/sidemenu/ionic.starter.json
- react/official/tabs/ionic.starter.json
This PR updates our CI workflow to automatically test the React and React Vite starter app spec/e2e tests.
The following changes have been made in support of this:
1. The workflow matrix explicitly lists each app to test. This is not necessary, but this will significantly speed up the overall run time. Otherwise we'll have to build and test 8 tests sequentially.
> test(react): test react apps

- angular-standalone/base/package.json
- angular-standalone/base/src/theme/variables.scss
- angular/base/package.json
- angular/base/src/theme/variables.scss
- react-vite/base/package.json
- react-vite/base/src/theme/variables.css
- vue-vite/base/package.json
- vue-vite/base/src/theme/variables.css
Removes the manual opt-in for dynamic font scaling. This behavior is automatic in v8.
> chore: remove dynamic font scaling opt-in
