ionic-team/starters

.gitmodules
I'm not sure this has to be in this repository, but it seems to be the only way to run `ionic start myApp oktadeveloper/jhipster`. If there's another way to run that command and pull from https://github.com/oktadeveloper/ionic-jhipster-starter, I'd love to hear about it!
=> Add Ionic starter for JHipster

ionic-angular/official/super/src/providers/api/api.ts
HttpParams class is immutable - all mutation operations return a new instance.
@see https://angular.io/api/common/http/HttpParams
=> Fix HTTP GET request params modification

angular/official/blank/src/app/app.module.ts, angular/official/blank/src/app/pages/home/home.page.scss, angular/official/blank/src/app/pages/pages.module.ts
Angular CLI can't judge `pages` and check `@angular/router`.
So I think Ionic CLI's `page` concentrate page.module.ts. and match selector name. ex) `app-page-home`
fix https://github.com/ionic-team/ionic-cli/issues/3019#issuecomment-375595052
=> propose: add page.module.ts

integrations/cordova/config.xml
Run with current Cordova tooling (Cordova CLI 8.0.0, Cordova Android 7.1.0) you currently get this error on build:
```
[cordova]
[cordova] :app:processDebugManifest FAILED
[cordova]       uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:CordovaLib] C:\Projects\Ionic Demo Projects\ionic-cordova-push-onesignal\platforms\android\CordovaLib\build\intermediates\manifests\full\debug\AndroidManifest.xml as the library might be using APIs not available in 16
[cordova]       Suggestion: use a compatible library with a minSdk of at most 16,
[cordova]               or increase this project's minSdk version to at least 19,
[cordova]               or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)
[cordova]
[cordova] …
```
=> chore(cordova): increase android-minSdkVersion from 16 to 19

angular/official/blank/src/app/components/components.module.ts
If @NgModule doesn't have IonicModule, @NgModule needs CUSTOM_ELEMENTS_SCHEMA.
=> fix(components) : add IonicModule

angular/official/blank/src/app/components/components.module.ts, angular/official/blank/src/app/pages/pages.module.ts
`<** [(ngModel)]="hoge">` require `FormsModule`.  ( `**` example `ion-input` ).
I think it is better to be default.
=> fix(ngModule): add FormsModule

angular/official/sidemenu/src/app/app.component.html, angular/official/sidemenu/src/app/pages/list/list.page.html
This PR fixes two things:
`
1. Removes the ion-back-button on the list page (we might have to add this back when list navigation is implemented, not totally sure at the moment)
2. Navigations from the sidemenu now are `root` navigations so that they work just like they did in v3
=> fix(sidemenu): menu navigations are root

angular/base/tslint.json
If migrate v3 to v4, all page component name is "page-*". So I think this is no need to change everything.
=> chore(tslint): allow component-selector "page-**"

angular/official/tabs/src/app/tabs/tabs.router.module.ts
example.com redirect `example.com/tabs/(home:home)` . but `example.com/tabs` display blank page. so add redirect.
=> fix(angular/tabs): redirect `example.com/tabs/` to (home:home)

angular/base/package.json, angular/base/src/global.scss
My updated package.json
{ "name": "someApp", "version": "0.0.1", "author": "Ionic Framework", "homepage": "http://ionicframework.com/", "scripts": { "ng": "ng", "start": "ng serve", "build": "ng build", "test": "ng test", "lint": "ng lint", "e2e": "ng e2e" }, "private": true, "dependencies": { "@angular/common": "~6.1.1", "@angular/core": "~6.1.1", "@angular/forms": "~6.1.1", "@angular/http": "~6.1.1", "@angular/platform-browser": "~6.1.1", "@angular/platform-browser-dynamic": "~6.1.1", "@angular/router": "~6.1.1", "@ionic-native/core": "5.0.0-beta.15", "@ionic-native/splash-screen": "5.0.0-beta.15", "@ionic-native/status-bar": "5.0.0-beta.15", "@ionic/angular": "^4.0.0-beta.7", "core-js": "^2.5.3", "rxjs": "^6.3.0", "zone.js": "^0.8.26" }, "devDependencies": { …
=> fix(angular/css) update css references based on 4.0.0-beta.6 changes

angular/base/src/karma.conf.js
Actually the coverage report will be created inside the `src` folder and not outside of it.
=> fix(angular): add correct coverage report path

angular/base/src/polyfills.ts
- docs: fix broken links to angular.io
- remove redundant reflect polyfill
- add comment for support `Fetch as Google`   ref: https://github.com/ionic-team/starters/pull/168
follow: https://github.com/angular/angular-cli/commits/4d46c4ac492e2ff460a52ca2a3f316c554df1521/packages/schematics/angular/application/files/src/polyfills.ts
=> refactor(polyfills): Follow Angular

angular/official/tabs/src/app/contact/contact.page.html
Prior to this modification, the migration linting tool generates errors about missing ion-labels. Kind of embarrassing when using this as a starting point for a migration.  :)
=> fix(tabs-starter): follow v4 migration guide

angular/official/blank/src/app/app-routing.module.ts, angular/official/sidemenu/src/app/app-routing.module.ts
This PR adds the preloading strategy to the blank and sidemenu starters (it is already there in the tabs starter).
This was discussed in the comments of the recent blog post: 
https://blog.ionicframework.com/how-to-lazy-load-in-ionic-angular/
@elylucas
=> fix(): use preloading strategy in all starters

integrations/cordova/config.xml, integrations/cordova/resources/android/xml/network_security_config.xml
Starting with Android 9, cleartext support is disabled by default. We
need to allow it again so livereload continues to work with `ionic
cordova run android`.
In CLI 5, the default host for the devserver is `localhost`, and traffic
on the devserver port is forwarded by native-run.
ref: https://github.com/ionic-team/ionic-cli/issues/3759
ref: https://developer.android.com/training/articles/security-config
=> fix(cordova): allow cleartext on localhost

react/official/sidemenu/src/components/Menu.tsx, react/official/tabs/src/pages/Tab2.tsx
`onClick` handlers are functional but they are not accessible.  Replace them with `Link` to create accessible anchor tags.
FYI: I was not able to figure out how to use Link tags with the individual tabs. Wrapping the tabs in Links made them disappear.  Wrapping the content of the tabs in `Links` worked but affected the styling.
Fixes #823
=> fix: replace onclick handlers with links for accessibility

angular/official/blank/src/app/home/home.page.spec.ts, angular/official/sidemenu/src/app/home/home.page.spec.ts, angular/official/sidemenu/src/app/list/list.page.spec.ts, angular/official/tabs/src/app/tab1/tab1.page.spec.ts, angular/official/tabs/src/app/tab2/tab2.page.spec.ts, angular/official/tabs/src/app/tab3/tab3.page.spec.ts
Updated how the tests are set up in the starters such that the Ionic components hydrate. The thread of discussion for this can be found here: https://ionicteam.slack.com/archives/C7CGXAVTL/p1564506798491300
=> fix(angular): update unit tets so components hydrate

angular/base/package.json
It was in both dependencies and devDependencies of package.json and npm was giving a warning. I removed it from dependencies and kept it in devDependencies.
=> Remove duplicate @angular/compiler dependency

react/official/sidemenu/src/App.tsx, react/official/sidemenu/src/components/Menu.tsx
In addition to the error you run into all sorts of issues when adding a page not using the `Page` component. I think it's something with calling `setSelectedPage` in the `render` of the `Route` component, causing the component to reload and `render` to be called again often for the previous page instead of the new page.
fixes #1171
=> fixes #1171

angular/base/src/theme/variables.scss, angular/official/blank/src/app/home/home.page.scss, angular/official/list/src/app/home/home.page.scss, angular/official/sidemenu/src/app/folder/folder.page.scss, angular/official/tabs/src/app/tab1/tab1.page.scss, angular/official/tabs/src/app/tab2/tab2.page.scss, angular/official/tabs/src/app/tab3/tab3.page.scss, react/base/src/theme/variables.css, react/official/blank/src/pages/Home.css, react/official/list/src/pages/Home.css, react/official/sidemenu/src/pages/Page.css, react/official/tabs/src/pages/Tab1.css, react/official/tabs/src/pages/Tab2.css, react/official/tabs/src/pages/Tab3.css
These two patches were added due to bugs in Ionic that we were unable to resolve in time for v5.0. They have since been resolved in patch updates to v5.
Toolbar bg fix: https://github.com/ionic-team/ionic/commit/f6c3ba7e5af2af9e32f75306cde7704509e82263#diff-222b13366c611b4ad640fa4c02f38ca8
Title color fix: https://github.com/ionic-team/ionic/commit/794c3d4e9608968d8d5ef8b77f9b024fa0131572#diff-222b13366c611b4ad640fa4c02f38ca8
=> chore(): remove unneeded toolbar and large title patches

angular/base/tslint.json
Now, sample of Ionic Documentation is warned from tslint. 
For examle:
```ts
const alert = await this.alertController.create({
header: 'Confirm!',
message: 'Message <strong>text</strong>!!!',
buttons: [
{
text: 'Cancel',
role: 'cancel',
cssClass: 'secondary',
handler: (blah) => {
console.log('Confirm Cancel: blah');
}
}, {
text: 'Okay',
handler: () => {
console.log('Confirm Okay');
}
}
]
});
```
tslint require `object-literal-sort-keys` :
```ts
const alert = await this. alertController.create({
buttons: [
{
cssClass: 'secondary',
handler: (blah) => {
console.log('Confirm Cancel: blah');
},
role: 'cancel',
text: 'Cancel',
}, {
handler: () => {
console.log('Confirm Okay');
},
text: 'Okay',
},
],
header: 'Confirm!',
message: 'Message <strong>text</strong>!!!',
});
```
But I feel this code is …
=> fix(angular): add tslint rule sort-keys false

angular/base/tsconfig.app.json
It appears I was a little too aggressive with https://github.com/ionic-team/starters/pull/1274. This PR fixes things so tests aren't included and files that are lazy-loaded are compiled.
=> Allow lazy-loaded files and exclude tests

react/official/sidemenu/src/components/Menu.tsx
I noticed the react starter for sidemenu made a point to import icons for both iOS and MD but only the iOS icons were used on the menu for both platforms.
=> fix(react): sidemenu imported ios and md icons but only used ios on both

integrations/cordova/config.xml
in cordova-android 9, the minSdkVersion will be bumped to 22, so having it set to 19 here will cause issues
in cordova-android 8, the minSdkVersion is 19, so no preference is needed 
because of that, I think it's better to not set the preference and let the cordova-android version used decide
=> chore: remove android-minSdkVersion

angular/base/e2e/protractor.conf.js
This fixes the following warning in the console when running `npm run e2e`:
```
WARN: jasmine-spec-reporter 'displayStacktrace' option supports value ('none', 'raw', 'pretty'), default to 'none'
```
=> Change Protractor to use raw for stacktrace

angular/base/package.json
karma-jasmine-html-reporter 1.6.0 was released as it requires jasmine-core >=3.7.1, so npm install is failing on newly created angular apps
another option is to change `"karma-jasmine-html-reporter": "^1.5.0"` to `"karma-jasmine-html-reporter": "~1.5.0",`
=> fix(angular): Update jasmine-core to 3.7.1

angular/base/package.json
newer versions fail to install on npm 7
=> fix(angular): use @angular-devkit/build-angular 0.1102.10 to resolve peer dependency issues

vue/official/tabs/src/views/Tabs.vue
Do not merge until 5.6.10 (this week)
=> fix(vue): update tabs usage for Framework v5.6.10

angular/base/package.json
latest `karma-jasmine-html-reporter` requires `jasmine-core` >= 3.8 (latest at the moment), so the starter template fails to install on npm 7
=> fix(angular): Update jasmine-core for npm 7

.circleci/config.yml, vue/base/package.json
Vue 3.2 requires Typescript 4.1+, otherwise you will get compilation errors.
I also added `-- --current` to have the starters built against the PR rather than `main` because `main` will install Vue 3.2 with Typescript 3.x, causing the build to fail.
=> fix(vue): bump typescript version for vue 3.2

vue/base/package.json
Vue CLI Server v4 has an optional dependency on `vue-loader-v16`. This was moved to optional dependencies to fix an issue with npm 5.6: https://github.com/vuejs/vue-cli/issues/5715
Unfortunately, this package is actually required to build a Vue app. Installing `npm install --no-optional` and then `npm run build` will cause the build to fail due to the missing `vue-loader-v16` package.
Appflow currently uses this `--no-optional` flag and Vue starters are failing to build as a result. I am making this change for now, and it will be removed when Ionic 6 ships. In Ionic 6 we are using Vue CLI v5 which does not depend on `vue-loader-v16` at all.
=> fix(vue): add vue loader to avoid crashing on appflow

react/base/package.json
Workaround for https://github.com/facebook/create-react-app/issues/11773#issuecomment-996540501. Also, react-scripts 5 is latest so we should be shipping this with Ionic apps anyways.
Related Ionic issue: https://github.com/ionic-team/ionic-framework/issues/24479
=> chore(react): bump react-scripts to v5

angular/base/.gitignore
The .angular directory is being committed to repos in Ionic starter apps with Angular 13 when it should not be.
Closes #1710
=> fix(angular): add .angular to gitignore

integrations/cordova/config.xml
cordova-android 10 loads from `https://localhost` by default, but cordova-plugin-ionic-webview defaults to http if the scheme is not set which causes CORS problems when accessing local files converted with `convertFileSrc` function.
By setting the scheme to http, cordova will load `http://localhost`, so there won't be CORS errors with local files.
=> set android scheme to http

angular/official/tabs/src/app/tab3/tab3.module.ts
This PR remove duplicated routing in `tab3.module.ts` added by #1225
=> fix(angular): remove duplicate routing modules

vue/base/.browserslistrc
Updates the browserslist file in accordance with the Ionic v6 browser support: https://ionicframework.com/docs/reference/browser-support
See: https://forum.ionicframework.com/t/ionic-6-default-project-white-screen-on-android-30-or-below-when-using-prod/228087/10 for more information
=> chore(vue): update browserslist

src/commands/deploy.ts
This will omit system-specific metadata such as user ID and group ID from the tarball. This will prevent recent versions of Git from complaining about "dubious ownership in repository" if a starter template is extracted by the root user.
=> Make tarballs portable

angular/official/list/src/app/message/message.component.html, angular/official/list/src/app/view-message/view-message.page.html, angular/official/sidemenu/src/app/app.component.html, angular/official/tabs/src/app/tabs/tabs.page.html, react/official/list/src/pages/ViewMessage.tsx, react/official/sidemenu/src/components/Menu.tsx, react/official/tabs/src/App.tsx, vue/official/list/src/components/MessageListItem.vue, vue/official/list/src/views/ViewMessagePage.vue, vue/official/sidemenu/src/App.vue, vue/official/tabs/src/views/TabsPage.vue
All icons used in the starters are decorative, and thus should not be announced by screen readers.
=> fix(angular, react, vue): add aria-hidden to all ion-icons

react/base/package.json
Running an app in development mode omits polyfills/transpiling necessary for an app to run on older versions of browsers. This PR updates the browserslist config for React to use the same config across dev and prod.
=> fix(react): browserslist uses same config for dev and prod

angular/base/angular.json, angular/base/package.json
Updates the Angular starter app to use standalone components by default. We had done most of the work in a previous commit, but we forgot to update the `angular.json` file change for `@ionic/angular-toolkit` support.
=> fix(angular): use standalone components

README.md
This fixes some links in the docs, most notably the one to the getting started guide. I'm not sure if we need some sort of redirect to fix this on the other side or not, since other things may be linking to https://ionicframework.com/getting-started/.
I removed the dependabot because it was broken. If there's a better fix, let me know.
=> fix(docs): update links in readme

.github/workflows/main.yml
A Vue/Vite dependency is using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing which is not supported in the version of node that our GitHub Actions scripts use. This PR bumps the scripts to use node 16 which supports nullish coalescing.
However, legacy starter apps such as `ionic-angular` and `ionic1` do not support node 16. As a result, this PR does two things:
1. Creates a legacy test step that runs node 14 for ionic-angular and ionic1 projects
2. Updates the non-legacy test step to run node 16 for modern projects.
=> chore(ci): use node 16

.github/workflows/main.yml
This PR updates the following GitHub Action packages:
1. `actions/checkout@v3`
2. `actions/setup-node@v3`
3. `actions/upload-artifact@v3`
4. `actions/download-artifact@v3`
5. `aws-actions/configure-aws-credentials@v2`
Main motivation is to account for the `save-state` and `set-output` removal on May 31, 2023: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> chore(ci): update action versions

react/base/.gitignore
When moving to Vite for the React starters, the output directory for the compiled output changed from `/build` to `/dist`. This PR updates the `.gitignore` to include the new output directory. The old directory remains in the `.gitignore` as I am unsure if all templates the base template is used with, is on Vite. 
Resolves: #1776
=> fix(react): gitignore dist output

angular-standalone/official/blank/src/app/home/home.page.spec.ts, angular-standalone/official/list/src/app/home/home.page.spec.ts, angular-standalone/official/sidemenu/src/app/app.component.spec.ts, angular-standalone/official/tabs/src/app/explore-container/explore-container.component.spec.ts, angular-standalone/official/tabs/src/app/tab1/tab1.page.spec.ts, angular-standalone/official/tabs/src/app/tab2/tab2.page.spec.ts, angular-standalone/official/tabs/src/app/tab3/tab3.page.spec.ts, angular-standalone/official/tabs/src/app/tabs/tabs.page.spec.ts, angular/official/sidemenu/src/app/app.component.spec.ts
Resolves #1767 
- Removes unused imports
- Removes unnecessary `async` modifiers
- Standardizes the spec test template for standalone examples
=> chore(angular): standardized approach for spec tests

README.md
We haven't used CircleCI in years. Let's remove the failing badge.
=> chore: remove circleci badge

.github/workflows/main.yml, vue-vite/official/blank/ionic.starter.json, vue-vite/official/list/ionic.starter.json, vue-vite/official/sidemenu/ionic.starter.json, vue-vite/official/tabs/ionic.starter.json, vue/official/blank/ionic.starter.json, vue/official/list/ionic.starter.json, vue/official/sidemenu/ionic.starter.json, vue/official/tabs/ionic.starter.json
This PR updates our CI workflow to automatically test the Vue and Vue Vite starter app spec/e2e tests.
The following changes have been made in support of this:
1. The workflow matrix explicitly lists each app to test. This is not necessary, but this will significantly speed up the overall run time. Otherwise we'll have to build and test 8 tests sequentially.
Note: Cypress with Vue CLI was hanging indefinitely. I tried updating both Cypress and Node, but was unable to resolve the issue. Given that the Vue CLI apps are in maintenance mode, I opted to skip running the E2E tests (the spec tests are still run as is a compilation test)
=> test(vue): test vue apps

.github/workflows/main.yml, angular-standalone/base/src/app/app.component.spec.ts, angular-standalone/official/blank/ionic.starter.json, angular-standalone/official/blank/src/app/home/home.page.spec.ts, angular-standalone/official/list/ionic.starter.json, angular-standalone/official/list/src/app/app.component.spec.ts, angular-standalone/official/sidemenu/ionic.starter.json, angular-standalone/official/sidemenu/src/app/app.component.spec.ts, angular-standalone/official/sidemenu/src/app/folder/folder.page.spec.ts, angular-standalone/official/tabs/ionic.starter.json, angular-standalone/official/tabs/src/app/explore-container/explore-container.component.spec.ts, angular-standalone/official/tabs/src/app/tab1/tab1.page.spec.ts, angular-standalone/official/tabs/src/app/tab2/tab2.page.spec.ts, angular-standalone/official/tabs/src/app/tab3/tab3.page.spec.ts, angular-standalone/official/tabs/src/app/tabs/tabs.page.spec.ts, angular/official/blank/ionic.starter.json, angular/official/list/ionic.starter.json, angular/official/sidemenu/ionic.starter.json, angular/official/tabs/ionic.starter.json
This PR updates our CI workflow to automatically test the Angular and Angular Standalone starter app spec/e2e tests.
The following changes have been made in support of this:
1. The workflow matrix explicitly lists each app to test. This is not necessary, but this will significantly speed up the overall run time. Otherwise we'll have to build and test 8 tests sequentially.
=> test(angular): test angular apps

angular-standalone/official/tabs/src/app/tabs/tabs.page.html, angular/official/tabs/src/app/tabs/tabs.page.html
resolves #1796
The tab buttons in the Angular tabs app were missing `href` which prevented the tab buttons from being keyboard accessible.
=> fix(angular): tab buttons have href

angular/base/package.json
The `package.json` has a duplicate `@angular/compiler` dependency. This should be a dependency of the project, not a dev dependency (Running `ng new` has the compiler as a dependency).
=> fix(angular): remove duplicate compiler dependency

angular-standalone/base/package.json
The `package.json` has a duplicate `@angular/compiler` dependency. This should be a dependency of the project, not a dev dependency (Running `ng new` has the compiler as a dependency).
=> fix(angular-standalone): remove duplicate compiler dependency

angular-standalone/base/src/theme/variables.scss, angular/base/src/theme/variables.scss, react-vite/base/src/theme/variables.css, vue-vite/base/src/theme/variables.css
Enables the default font for dynamic font scaling.
This PR uses a link to documentation that has not been merged/released in production (yet). The docs that it will resolve will be: https://ionic-docs-git-feature-75-ionic1.vercel.app/docs/layout/dynamic-font-scaling
Testing:
- Run `npm run starters:build -- --current`
- Navigate into each `build/*` directory for the effected starters
- Install dependencies
- Run the app
- Verified that the `html` node has the new variable styles
Dev-build for font-scaling:`7.3.4-dev.11695654072.17597cce`
=> chore: enable dynamic font for starter templates

angular-standalone/base/src/global.scss, angular/base/src/global.scss
`global.scss` is mixing simple and double quotes, so teams that use a code formatter tool like [Prettier](https://prettier.io/) need to make a useless commit to fix it when starting their project.
Btw thank you so much for Ionic and Capacitor, these tools make my life wonderful!
=> chore(angular): uniformize quote style

react-vite/base/.gitignore, react/base/.gitignore
`dist` was added to the regular react gitignore, I've removed it from there and added it to the react-vite template
=> fix(react): gitignore dist for vite

.github/workflows/main.yml
Deployment currently happens when all the tests are run. However, I failed to update the deploy step to only run once the tests are verified to all have passed (the "verify-test" and "verify-test-legacy") steps.
The current behavior shouldn't be causing issues, since tests must pass before PRs are merged anyways, but we should still wait for the verification step before deploying.
=> chore: deploy should run when tests pass

angular-standalone/base/.vscode/settings.json, angular/base/.vscode/settings.json
This PR updates the module and starter templates for Angular to ship with a default VSCode setting that prevents importing from invalid locations.
For example, the base projects using modules will ignore import recommendations from `@ionic/angular/standalone` and `@ionic/angular/common`. Standalone projects will ignore import recommendations from `@ionic/angular` and `@ionic/angular/common`.
=> fix(angular): prevent invalid import recommendations

.github/workflows/main.yml
Bumps Github Action workflow job steps to use v20 (other than the legacy job step).
=> chore(ci): bump workflows to run on node v20

vue-vite/base/package.json
Similar to #1819, the vue vite base project had a missing peer dependency requirement for `terser`. This caused certain package managers such as `yarn` or `pnpm` to fail building the app.
=> fix(vue-vite): add missing peer dependency

angular-standalone/base/package.json, angular/base/package.json
resolves #1742
`ts-node` is outdated, but it isn't actually used anywhere in the starter apps. This PR removes the dependency.
=> chore: remove ts-node

angular-standalone/base/angular.json, angular/base/angular.json
One of the issues I'm seeing devs run into with the Ionic 8 beta is with trying to override the default light theme. Devs are placing their overrides in `theme/variables.scss`. However, our `angular.json` config has it so that `theme/variables.scss` is loaded before `global.scss` (where the default light theme is imported).
Since both sets of styles target the same selector, they have the same specificity and the latest style to get added to the DOM wins (`global.scss` in this case). As a result, the custom styles do not apply.
This PR switches the order so `global.scss` is loaded first. This is really only needed for Ionic 8, so I could target the `feature-8.0` branch. However, I figured it would be good to get this change out sooner since devs testing the Ionic 8 beta may create fresh …
=> fix(angular): variables gets loaded after global

angular-standalone/base/package.json, angular-standalone/base/src/global.scss, angular/base/package.json, angular/base/src/global.scss, react-vite/base/package.json, react-vite/base/src/App.tsx, react-vite/official/blank/src/App.tsx, react-vite/official/list/src/App.tsx, react-vite/official/sidemenu/src/App.tsx, react-vite/official/tabs/src/App.tsx, vue-vite/base/package.json, vue-vite/base/src/main.ts
- Uses the latest version of `@ionic/<framework>@next` and `@ionic/<framework>-router@next`
- Renames `css/themes` to `css/palettes` for dark mode imports
=> refactor(apps): update paths and naming for latest v8

angular-standalone/base/.gitignore, angular/base/.gitignore, react-vite/base/.gitignore, react/base/.gitignore
`.nx` folder has crept in because of it's use in [@angular/es-lint](https://github.com/angular-eslint/angular-eslint).
=> fix(angular,react): ignore .nx files

angular-standalone/base/src/app/app.component.spec.ts, angular-standalone/official/list/src/app/app.component.spec.ts, angular-standalone/official/sidemenu/src/app/app.component.spec.ts, angular-standalone/official/sidemenu/src/app/folder/folder.page.spec.ts, angular-standalone/official/tabs/src/app/tabs/tabs.page.spec.ts, angular/official/sidemenu/src/app/app.component.spec.ts
RouterTestingModule was deprecated in v17.3.0 of Angular and marked as deprecate here: https://github.com/angular/angular/pull/54466
=> refactor(angular): migrate deprecated RouterTestingModule

angular-standalone/official/sidemenu/src/app/app.component.scss, angular/official/sidemenu/src/app/app.component.scss, react-vite/official/sidemenu/src/components/Menu.css, vue-vite/official/sidemenu/src/App.vue
The step color token used on the sidemenu app was never updated to use the latest syntax. As a result, the border in dark mode always showed as the light mode fallback.
| Before | After |
| - | - | 
| ![Screenshot 2024-04-29 at 9 44 52 AM](https://github.com/ionic-team/starters/assets/2721089/bc8d5b23-5ee9-4b91-b9ab-8bf3f1cb5efc) | ![Screenshot 2024-04-29 at 9 44 39 AM](https://github.com/ionic-team/starters/assets/2721089/84265e4e-c599-4815-9b18-77b35ac732d5) |
=> fix: migrate sidemenu step color usage

angular/official/sidemenu/src/app/app.component.spec.ts
There's a test that is flaky that is only happening in Angular. Skipping for now until it can be fixed.
=> test(angular): skip menu labels test due to flakiness

react-vite/official/list/src/components/MessageListItem.css, react-vite/official/list/src/components/MessageListItem.tsx, react/official/list/src/pages/ViewMessage.tsx
The React list starter was not overriding the Ionic styles for label, resulting in it looking different compared to the Angular list starter. This updates the CSS to target an `IonItem` with an `id` so that the styles are properly overridden. Additionally, I updated the back button text for the `ViewMessage` view because it should only display on `ios` mode and it was displaying for `md`.
<table>
<thead>
<td>Before</td>
<td>After</td>
</thead>
<tbody>
<tr>
<td width="50%">
</td>
<td width="50%">
</td>
</tr>
<tr>
<td width="50%">
</td>
<td width="50%">
</td>
</tr>
</table>
=> fix(react): update list starter for correct styles and back button text

angular-standalone/base/angular.json
Angular standalone apps are creating the assets in a `browser` folder inside `www`, which is causing issues for Capacitor users as it expects the `index.html` to be at the root of the `www` folder.
This change prevents the creation of the `browser` folder.
=> fix(angular-standalone): prevent browser folder creation
